<!doctype html public "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml"><head><title>{if $pagetitle ne ""}{$pagetitle} - {/if}{$site_name}</title><meta name="description" content="{if $pagetitle ne ''}{$pagetitle} - {/if}{if $metadescription ne ''}{$metadescription} - {/if}{$site_name}/><meta name="keywords" content="{if $pagetitle ne ''}{$pagetitle},{/if}{if $metakeywords ne ''}{$metakeywords},{/if}{$site_name}/><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><script language="javascript" type="text/javascript" src="{$baseurl}/js/jquery-1.3.2.min.js"></script><link rel="alternate" type="application/rss+xml" title="RSS" href="{$baseurl}"/><meta http-equiv="x-ua-compatible" content="ie=7"/><link type="text/css" rel="stylesheet" href="{$cssurl}/css.php"/><link type="text/css" rel="stylesheet" href="{$cssurl}/style.php"/>{literal}<script language="javascript" type="text/javascript">function toggle(obj) {var el = document.getElementById(obj);if ( el.style.display != 'none' ) {$('#' + obj).slideUp();}else {$('#' + obj).slideDown();}}function tog(obj) {var el = document.getElementById(obj);if ( el.style.display != 'none' ) {$('#' + obj).hide();}else {$('#' + obj).show();} }</script>

<style media="screen" type="text/css">.cf:before, .cf:after{    content:"";    display:table;}.cf:after{    clear:both;}.cf{    zoom:1;} /* Form wrapper styling */.form-wrapper {    width: 805px;    padding: 5px;    margin: 50px auto 50px auto;    background: #cccccc;    xbackground: rgba(0,0,0,.2);    border-radius: 10px;    xbox-shadow: 0 1px 1px rgba(0,0,0,.4) inset, 0 1px 0 rgba(255,255,255,.2);}/* Form text input */ .form-wrapper input {    width: 330px;    height: 20px;    padding: 10px 5px;    float: left;        font: bold 15px 'lucida sans', 'trebuchet MS', 'Tahoma';    border: 0;    background: #eee;    border-radius: 3px 0 0 3px;	margin-left: 5px;      } .form-wrapper input:focus {    outline: 0;    background: #fff;    box-shadow: 0 0 2px rgba(0,0,0,.8) inset;} .form-wrapper input::-webkit-input-placeholder {   color: #999;   font-weight: normal;   font-style: italic;} .form-wrapper input:-moz-placeholder {    color: #999;    font-weight: normal;    font-style: italic;} .form-wrapper input:-ms-input-placeholder {    color: #999;    font-weight: normal;    font-style: italic;}/* Form submit button */.form-wrapper button {    overflow: visible;    position: relative;    float: right;    border: 0;    padding: 0;    cursor: pointer;    height: 40px;    width: 110px;    font: bold 15px/40px 'lucida sans', 'trebuchet MS', 'Tahoma';    color: #fff;    text-transform: uppercase;    background: #ff7e00;    border-radius: 0 3px 3px 0;          text-shadow: 0 -1px 0 rgba(0, 0 ,0, .3);}      .form-wrapper button:hover{         background: #ff7e00;}      .form-wrapper button:active,.form-wrapper button:focus{       background: #c42f2f;    outline: 0;   } .form-wrapper button:before { /* left arrow */    content: '';    position: absolute;    border-width: 8px 8px 8px 0;    border-style: solid solid solid none;    border-color: transparent #ff7e00 transparent;    top: 12px;    left: -6px;} .form-wrapper button:hover:before{    border-right-color: #ff7e00;} .form-wrapper button:focus:before,.form-wrapper button:active:before{        border-right-color: #c42f2f;}.form-wrapper button::-moz-focus-inner { /* remove extra button spacing for Mozilla Firefox */    border: 0;    padding: 0;} </style>{/literal}</head>


<body leftmargin="0" topmargin="0" rightmargin="0">	<div id="fb-root">	</div>	
{if $enable_fc eq "1"}	{literal}	<script src="http://connect.facebook.net/en_US/all.js"></script>	<script>	  FB.init({appId: '{/literal}{$FACEBOOK_APP_ID}{literal}', status: true,	           cookie: true, xfbml: true});	  FB.Event.subscribe('auth.login', function(response) {	  });	  	</script>	{/literal}	
{/if}	
<div id="loadme">	</div>	
<form name="langselecten" id="langselecten" method="post" style="padding:0; margin:0">				<input type="hidden" name="language" value="english" />	</form>	<form name="langselectes" id="langselectes" method="post" style="padding:0; margin:0">				<input type="hidden" name="language" value="spanish" />	
</form>	<form name="langselectfr" id="langselectfr" method="post" style="padding:0; margin:0">				<input type="hidden" name="language" value="french" />	
</form>	
{assign var="skyfallblue" value="1"}	<div class="common">		<div class="header-items-bar">						
<div class="op_layer_sign"><span class="silver_nn">							
{if $smarty.session.USERID ne ""}                               
 {literal}                                <script type="text/javascript">                                function loadContent(elementSelector, sourceURL) {                                $(""+elementSelector+"").load(""+sourceURL+"");                                }                                </script>                                {/literal}  
        <a id="IA_Login" href="{$baseurl}/account">{$lang1}</a>|<a href="javascript:loadContent('#loadme', '{$baseurl}/log_out');" class="last">{$lang151}</a>{else}<a id="IA_Login" href="{$baseurl}/login">{$lang46}</a>|<a href='{$baseurl}/signup'>{$lang76}</a>                             {/if}</span>						</div>				</div>		<div class="topmenu_op">			<div class="top_layer">			<a href="{$baseurl}/"><img class="thelogo" src="{$imageurl}/logo.png" width="259" height="75" border="0" alt="{$site_name|stripslashes}"/></a>			<span class="thenav"><a href="{$baseurl}/answer?filter=recent">recently asked</a>  <a href="{$baseurl}/answer?filter=found">recently found</a>  <a href="{$baseurl}/popular">popular</a>  <a href="{$baseurl}/ask">seeqe</a></span>							<div class="top_op">					<div class="op_layer">					</div>				</div>				<div class="cleartm">				</div>			</div>		</div>				
		
</div>	</div>